### ISSUE TITLE
Changes

### ISSUE THREAD

**Issue by TrySound** [75lb/transition-to-from-auto#1]
Nice thing! But for compatibility use get/set/remove/Attribute instead of dataset and detect transition:

```
var transition, transitionEnd;
(function () {
  var style= document.createElement('a').style, prop;
  if(style[prop = 'webkitTransition'] !== undefined) {
    transitionEnd = 'webkitTransitionEnd'
    transition = prop;
  }
  if(style[prop = 'transition'] !== undefined) {
    transitionEnd = 'transitionend'
    transition = prop;
  }
} ())
```

Let instead of selector using element object.

**Comment by TrySound** [comment]
And maybe window export better to name transitionAuto in new major version

**Comment by TrySound** [comment]
And in my practice sudo uses only for global installation

**Comment by TrySound** [comment]
Also for older browsers check transition variable and just add the value if it false.

**Comment by TrySound** [comment]
Maybe selector should be replaced with element option and receive string and element.

**Comment by 75lb** [comment]
hey bro, thanks for all the feedback! if you like, please fork, make some changes and submit a pull request! I will appreciate the help.. 

"sudo uses only for global installation" - on modern Macs there is no need to use `sudo` with `npm install -g`, although it is necessary on old macs and Linux (i believe)..

**Comment by TrySound** [comment]
I have Yosemite and I need to use sudo for global install.

**Comment by TrySound** [comment]
Maybe let by default use css style, not option?

**Comment by TrySound** [comment]
More often to-from-auto trick uses for slide effect like jQuery. So, maybe by default use 'height'?

**Comment by TrySound** [comment]
Okay, it's bad idea with css styles.

**Comment by TrySound** [comment]
But by default it should not use transition?

**Comment by TrySound** [comment]
Want to rename:
- to -> val
- property -> prop

because shorter and sensible.

**Comment by 75lb** [comment]
"I have Yosemite and I need to use sudo for global install." - maybe you should do a fresh install of Yosemite.. because by default, you do not need `sudo` to `npm install -g`.. i have Yosemite too.. i have not needed to use `sudo` for a long time - since before Lion.

**Comment by TrySound** [comment]
@75lb Maybe :)
