### ISSUE TITLE
Remove `transition: none 0s ease 0s;` after transition completes

### ISSUE THREAD

**Issue by JacobDB** [75lb/transition-to-from-auto#5]
I use this library for my mobile menu system, in order to animate open sub-menus when clicking on an arrow. I'd like to set the sub-menus to `visibility: hidden;` when closed and `visibility: visible;` when open. 

To do this, I set the default state of the element to have `transition: height 0.15s, visibility 0s 0.15s;`, and the active state of the element to have `transition: height 0.15s;`. This way, when the `is-active` class gets added (as soon as the element is triggered), the only property that transitions is the height, and when the `is-active` class gets removed, the height transitions, then the visibility gets set to hidden after the transition completes.

For a code example, see below:

    element {
        height: 0;
        visibility: hidden;
        transition: height 0.15s, visibility 0s 0.15s;
    }

    element.is-active { /* class gets added as soon as the element begins to transition */
        height: auto;
        visibility: visible;
        transition: height 0.15s;
    }

When using this library, it seems that `transition: none 0s ease 0s;` gets added to the element after the transition completes, which breaks my desired behavior. With this library enabled, it immediately triggers `visibility: hidden;` instead of waiting for the height transition to complete.

Why does this property get set this way? Would it be possible to simply remove the property after the transition ends?

I'll look in to using the `transition.end` functionality to do this myself, but it'd be nice if this "just worked."

**Comment by JacobDB** [comment]
I'm able to get this working if I use `!important` on my transition properties but I'd still like to know why this is set up the way that it is and if possible have it removed, as it seems unnecessary from my viewpoint.

**Comment by 75lb** [comment]
Closing - this library is no longer maintained.
